# Generated by Django 5.0.6 on 2025-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("price_band", models.CharField(max_length=50)),
                ("open_date", models.CharField(max_length=50)),
                ("close_date", models.CharField(max_length=50)),
                ("issue_size", models.CharField(max_length=50)),
                ("issue_type", models.CharField(max_length=50)),
                ("listing_date", models.CharField(max_length=50)),
                ("rhp_pdf", models.URLField(blank=True, null=True)),
                ("drhp_pdf", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
